# Railway用設定ファイル
# このファイルはRailwayデプロイ用の設定です

server:
  ip: 0.0.0.0
  port: 8000
  http_port: 8000
  websocket: "wss://xiaozhi-esp32-server2-production.up.railway.app/xiaozhi/v1/"
  vision_explain: "https://xiaozhi-esp32-server2-production.up.railway.app/mcp/vision/explain"
  timezone_offset: +8
  auth:
    enabled: false

log:
  log_format: "<green>{time:YYMMDD HH:mm:ss}</green>[{version}_{selected_module}][<light-blue>{extra[tag]}</light-blue>]-<level>{level}</level>-<light-green>{message}</light-green>"
  log_format_file: "{time:YYYY-MM-DD HH:mm:ss} - {version}_{selected_module} - {name} - {level} - {extra[tag]} - {message}"
  log_level: DEBUG
  log_dir: tmp
  log_file: "server.log"
  data_dir: data

delete_audio: true
close_connection_no_voice_time: 120
tts_timeout: 10
enable_stop_tts_notify: false

exit_commands:
  - "退出"
  - "关闭"

xiaozhi:
  type: hello
  version: 1
  transport: websocket
  audio_params:
    format: opus
    sample_rate: 16000
    channels: 1
    frame_duration: 60

wakeup_words:
  - "你好小智"
  - "嘿你好呀"
  - "你好小志"
  - "小爱同学"
  - "你好小鑫"
  - "你好小新"
  - "小美同学"
  - "小龙小龙"
  - "喵喵同学"
  - "小滨小滨"
  - "小冰小冰"

# 基本的な機能のみ有効化
selected_module:
  VAD: WebRTCVAD
  ASR: OpenAIASR
  LLM: OpenAILLM
  VLLM: ChatGLMVLLM
  TTS: OpenAITTS
  Memory: nomem
  Intent: function_call

# LLM設定（OpenAI）
LLM:
  OpenAILLM:
    type: openai
    model_name: gpt-4o-mini
    url: https://api.openai.com/v1/
    api_key: ${OPENAI_API_KEY}

# TTS設定（OpenAI）
TTS:
  OpenAITTS:
    type: openai
    voice: alloy
    output_dir: tmp/

# 音声活動検出
VAD:
  WebRTCVAD:
    type: webrtc
    aggressiveness: 2
    min_silence_duration_ms: 400

# 音声認識（OpenAI Whisper API）
ASR:
  OpenAIASR:
    type: openai
    base_url: https://api.openai.com/v1/audio/transcriptions
    model_name: whisper-1
    api_key: ${OPENAI_API_KEY}
    output_dir: tmp/

# 基本的な機能のみ
Intent:
  function_call:
    type: function_call
    functions:
      - change_role
      - get_weather
      - get_news_from_newsnow

# 記憶機能は無効
Memory:
  nomem:
    type: nomem

# Character setting (Nekota style)
prompt: "You are nekota, a cute cat girl AI assistant. You have the gentleness and curiosity of a cat, and often use cute cat language like 'nya~' and 'nyan' when speaking."

# プラグイン設定
plugins:
  get_weather: {"api_host":"mj7p3y7naa.re.qweatherapi.com", "api_key": "a861d0d5e7bf4ee1a83d9a9e4f96d4da", "default_location": "东京" }
  get_news_from_newsnow:
    url: "https://newsnow.busiyi.world/api/s?id="
    news_sources: "澎湃新闻;百度热搜;财联社"
